//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.DbLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pmsiteEntities : DbContext
    {
        public pmsiteEntities()
            : base("name=pmsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<logEventos> logEventos { get; set; }
        public DbSet<pm_events> pm_events { get; set; }
        public DbSet<pm_rsvp> pm_rsvp { get; set; }
        public DbSet<pm_speaker> pm_speaker { get; set; }
        public DbSet<pm_speakers_event> pm_speakers_event { get; set; }
        public DbSet<pm_user> pm_user { get; set; }
        public DbSet<rolesUsuario> rolesUsuario { get; set; }
        public DbSet<users> users { get; set; }
    }
}
