//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class logEventos
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public string evento { get; set; }
        public System.DateTime fecha { get; set; }
        public string trackEvent { get; set; }
        public string userName { get; set; }
    }
}
