//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_events
    {
        public pm_events()
        {
            this.pm_rsvp = new HashSet<pm_rsvp>();
            this.pm_speakers_event = new HashSet<pm_speakers_event>();
        }
    
        public int uid { get; set; }
        public string name { get; set; }
        public System.DateTime eventDate { get; set; }
        public string eventDescription { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual ICollection<pm_rsvp> pm_rsvp { get; set; }
        public virtual ICollection<pm_speakers_event> pm_speakers_event { get; set; }
    }
}
