//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_rsvp
    {
        public int event_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public bool active { get; set; }
    
        public virtual pm_events pm_events { get; set; }
        public virtual pm_user pm_user { get; set; }
    }
}
