//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_speaker
    {
        public pm_speaker()
        {
            this.pm_speakers_event = new HashSet<pm_speakers_event>();
        }
    
        public int uid { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
    
        public virtual ICollection<pm_speakers_event> pm_speakers_event { get; set; }
    }
}
