//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_speakers_event
    {
        public int speaker_id { get; set; }
        public int event_id { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual pm_events pm_events { get; set; }
        public virtual pm_speaker pm_speaker { get; set; }
    }
}
